name: Build Windows Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PyQt5 opencv-python numpy opencv-python

      - name: Build executable
        run: |
          pyinstaller main.py --onefile --windowed --name=CVFrameLabeler --icon=icon.ico

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: CVFrameLabeler
          path: dist/
